### ISSUE TITLE
Undefined index: q in Drupal\eva\Plugin\views\display\Eva->execute()

### ISSUE THREAD

**Issue by lrdueck** [ahebrank/eva#3]
I'm getting the following PHP notice:

Notice: Undefined index: q in Drupal\eva\Plugin\views\display\Eva->execute() (line 292 of modules/eva-8.x-1.x/src/Plugin/views/display/Eva.php).
Drupal\eva\Plugin\views\display\Eva->execute() (Line: 1592)
Drupal\views\ViewExecutable->executeDisplay('entity_view_1') (Line: 116)
eva_entity_view_alter(Array, Object, Object) (Line: 492)
Drupal\Core\Extension\ModuleHandler->alter(Array, Array, Object, Object) (Line: 273)
Drupal\Core\Entity\EntityViewBuilder->buildMultiple(Array) (Line: 208)
Drupal\Core\Entity\EntityViewBuilder->build(Array)
call_user_func(Array, Array) (Line: 384)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 200)
Drupal\Core\Render\Renderer->render(Array, ) (Line: 231)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 577)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 232)
Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object, Object) (Line: 122)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 95)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object) (Line: 116)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.view', Object) (Line: 144)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 62)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 62)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 53)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 103)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 82)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 55)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 637)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

This seems to happen for every EVA field. I can fix this particular issue by adding an if check to see if it exists, but it just creates new errors. I feel like there is something else going on.

**Comment by ahebrank** [comment]
Thanks--haven't seen this come up in testing so I'd be interested in knowing more about how you're setting up this view and where it's embedded.

But per https://www.drupal.org/node/1659562, I've swapped out $_GET['q'] for current_path(), so maybe that will be enough to resolve this.

**Comment by ahebrank** [comment]
... and replaced current_path() with the current Symfony equivalent.

**Comment by spacereactor** [comment]
thank, i just try https://simplytest.me/ 8.1.0-rc1 create a basic node, entity content reference 30 articles node to that singel basic node. create a view eva with ajax on, limit to pager 5 items. The basic node can only display the first 5 articles AND next 5 articles, and ajax break after that. doesn't let you display previous page or next page

**Comment by ahebrank** [comment]
I think this may be specific to 8.1rc.  See #4.

**Comment by lrdueck** [comment]
Beautiful! I added the latest commits and the above error went away. Now I am getting this error:

Notice: Undefined index: #name in _views_slideshow_preprocess_views_view_slideshow() (line 52 of modules/views_slideshow/views_slideshow.theme.inc).
_views_slideshow_preprocess_views_view_slideshow(Array) (Line: 148)
template_preprocess_views_view_slideshow(Array, 'views_view_slideshow', Array) (Line: 293)
Drupal\Core\Theme\ThemeManager->render(Array, Array) (Line: 438)
Drupal\Core\Render\Renderer->doRender(Array) (Line: 451)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 200)
Drupal\Core\Render\Renderer->render(Array) (Line: 472)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 89)
__TwigTemplate_0ec69db1d7ca63a8213da8f7b980cf0835b05f914602149aac373d434fb21a5c->doDisplay(Array, Array) (Line: 381)
Twig_Template->displayWithErrorHandling(Array, Array) (Line: 355)
Twig_Template->display(Array) (Line: 366)
Twig_Template->render(Array) (Line: 64)
twig_render_template('modules/eva-8.x-1.x/templates/eva-display-entity-view.html.twig', Array) (Line: 390)
Drupal\Core\Theme\ThemeManager->render(Array, Array) (Line: 438)
Drupal\Core\Render\Renderer->doRender(Array) (Line: 451)
Drupal\Core\Render\Renderer->doRender(Array) (Line: 451)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 200)
Drupal\Core\Render\Renderer->render(Array) (Line: 472)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 105)
__TwigTemplate_56c197b1bfc1c513053fcec14fd062ae5055bf07d253f25a6e7d79cec6eba86a->doDisplay(Array, Array) (Line: 381)
Twig_Template->displayWithErrorHandling(Array, Array) (Line: 355)
Twig_Template->display(Array) (Line: 366)
Twig_Template->render(Array) (Line: 64)
twig_render_template('themes/weavers/templates/node--home-page.html.twig', Array) (Line: 390)
Drupal\Core\Theme\ThemeManager->render('node', Array) (Line: 438)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 200)
Drupal\Core\Render\Renderer->render(Array, ) (Line: 231)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 577)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 232)
Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object, Object) (Line: 122)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 95)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object) (Line: 116)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.view', Object) (Line: 144)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 62)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 62)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 53)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 103)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 82)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 55)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 637)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

I am using EVA with a Slideshow. Is the problem with EVA or with views_slideshow?

**Comment by ahebrank** [comment]
It looks like more a problem with views_slideshow -- they have a notes about it on the line that's throwing the error:

```
    // @todo: This #name element is not available of Views edit page.
    $vss_id = $view->element['#name'] . '-' . $view->current_display;
```

They should probably use something like `$view->storage->get('id')` instead of trying to pull from the render array.

Closing out this issue since the original problem seems to be resolved.
